#!/bin/sh
echo "Compiling site... \n"
bundle exec jekyll build

echo "Running stats on CSS... \n"
parker _site/assets/css

echo "Testing SCSS...\n"
stylelint assets/css/**/*.scss -c .stylelintrc.json -s scss

echo "\nTesting HTML...\n"
bundle exec htmlproofer ./_site --check-opengraph true --check-html true --http-status-ignore "408,301,0"  --empty-alt-ignore true --external_only true
